### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by niksurff** [awoojs/awoo#78]
What's the recommended way of handling errors inside (`async`) plugins?

Given an example plugin like the following:

``` javascript
async function plugin() {
  // uncomment next line to throw error in plugin initialization phase
  // throw new Error("plugin INIT error")

  return async files => {
    throw new Error("plugin EXEC error")
  }
}
```

I'll get an `UnhandledPromiseRejectionWarning` in both error cases. These are notoriously hard to debug. Should these errors be caught by awoo or the plugin?

Still getting confused with error handling when using promises&hellip;

Thanks a bunch  :octocat:

**Comment by zipang** [comment]
I can add other examples that throw that infamous `UnhandledPromiseRejectionWarning`

For instance : 
1. Forgetting to return the site once configured : 
```js
awoo(site => {
  site.config(myConfig);
  site.use(myPlugin);
})
```

2. Trying to build a plugin like in Metalsmith
```js
awoo(site => {
  site.config(myConfig);
  site.use(myPlugin(pluginCfg));
  return site;
})
```

These rather frequent errors give way to an exception that is really difficult to understand because (depending on the version of node) there is not even an accurate stack trace for the error.
